### ISSUE TITLE
did you compared your performance with DataSqueezer?

### ISSUE THREAD

**Issue by Sandy4321** [nlarusstone/corels#10]
did you compared your performance with DataSqueezer?

https://sci2s.ugr.es/keel/pdf/algorithm/articulo/DataSqueezer.pdf
https://www.ncbi.nlm.nih.gov/pubmed/16468565

 Highly scalable and robust rule learner performance evaluation and comparison

it may be described in this book
https://www.amazon.com/Data-Mining-Knowledge-Discovery-Approach/dp/0387333339%3FSubscriptionId%3DAKIAJGYQBXXGETPQMZBA%26tag%3Dspeakerfile-20%26linkCode%3Dsp1%26camp%3D2025%26creative%3D165953%26creativeASIN%3D0387333339

**Comment by nlarusstone** [comment]
We did not, but feel free to do so and post the results here!
