### ISSUE TITLE
did you compared your code with  ICRM :  Interpretable Classification Rule Mining Algorithm

### ISSUE THREAD

**Issue by Sandy4321** [nlarusstone/corels#11]
ICRM -- An Interpretable Classification Rule Mining Algorithm

https://www.researchgate.net/publication/232633984_A_Survey_of_Discretization_Techniques_Taxonomy_and_Empirical_Analysis_in_Supervised_Learning

code
https://waikato.github.io/weka-wiki/packages/unofficial/

![image](https://user-images.githubusercontent.com/11426119/63625863-f708e180-c5ce-11e9-9140-f4c10fe7a5da.png)

**Comment by nlarusstone** [comment]
We have not, as we are not a rule mining technique, but rather a rule list generation technique. Feel free to substitute ICRM for FPGrowth to use with `CORELS` though!

**Comment by Sandy4321** [comment]
and what about this
https://github.com/jirifilip/pyARC
an implementation of CBA (Classification Based on Assocation) algorithm

**Comment by nlarusstone** [comment]
That's a greedy method, so we should equal or outperform it in all cases. Please let us know if you find that not to be the case!

**Comment by Sandy4321** [comment]
Feel free to substitute ICRM for FPGrowth to use with CORELS though!
can you help to understand what do you mean?
