### ISSUE TITLE
Typo in Rule List introduction page

### ISSUE THREAD

**Issue by yujia21** [nlarusstone/corels#13]
Minor typo on [this page](https://corels.eecs.harvard.edu/corels/whatarerulelists.html): the last example should probably read "If age < 25 then predict likes sports = true" and not >.

**Comment by saligrama** [comment]
This should be an issue on saligrama/corels-ui. We will look into it and fix it shortly.

**Comment by nlarusstone** [comment]
Closing as an issue here. @yujia21 feel free to re-open at https://github.com/saligrama/corels-ui/
