### ISSUE TITLE
Cannot compile current code with older g++ version

### ISSUE THREAD

**Issue by eddelbuettel** [nlarusstone/corels#17]
*Context:*   R packages on Windows are currently still built with g++-4.9.3, so conformance with that (old) versions matters for a large number of users.   

*Problem:*  As can _e.g._ be validated with an old-enough Docker container (here `ubuntu:xenial`) where we can do `apt-get update; apt-get install g++-4.0` we see that compilation fails on

```sh
root@a60d5c9d8643:/work# g++-4.9 -std=c++11 -c cache.cpp -I .
In file included from /usr/include/c++/4.9/vector:65:0,
                 from utils.hh:7,
                 from cache.hh:3,
                 from cache.cpp:1:
/usr/include/c++/4.9/bits/stl_bvector.h: In instantiation of 'std::vector<bool, _Alloc>::size_type std::vector<bool, _Alloc>::max_size() const [with _Alloc = track_alloc<bool, (DataStruct)0>; std::vector<bool, _Alloc>::size_type = long unsigned int]':
/usr/include/c++/4.9/bits/stl_bvector.h:1158:20:   required from 'std::vector<bool, _Alloc>::size_type std::vector<bool, _Alloc>::_M_check_len(std::vector<bool, _Alloc>::size_type, const char*) const [with _Alloc = track_alloc<bool, (DataStruct)0>; std::vector<bool, _Alloc>::size_type = long unsigned int]'
/usr/include/c++/4.9/bits/vector.tcc:789:62:   required from 'void std::vector<bool, _Alloc>::_M_insert_aux(std::vector<bool, _Alloc>::iterator, bool) [with _Alloc = track_alloc<bool, (DataStruct)0>; std::vector<bool, _Alloc>::iterator = std::_Bit_iterator]'
/usr/include/c++/4.9/bits/stl_bvector.h:880:54:   required from 'std::vector<bool, _Alloc>::iterator std::vector<bool, _Alloc>::insert(std::vector<bool, _Alloc>::const_iterator, const bool&) [with _Alloc = track_alloc<bool, (DataStruct)0>; std::vector<bool, _Alloc>::iterator = std::_Bit_iterator; std::vector<bool, _Alloc>::const_iterator = std::_Bit_const_iterator]'
cache.hh:200:57:   required from here
/usr/include/c++/4.9/bits/stl_bvector.h:755:65: error: 'const _Bit_alloc_type' has no member named 'max_size'
       const size_type __asize = _M_get_Bit_allocator().max_size();
                                                                 ^
root@a60d5c9d8643:/work# 
```

where `/work` is the Docker mount of the `src/` directory of this repo.  I had tried various tricks first in getting the "cloud-based" Windows build services (i.e. win-builder and rhub) to build the package to no avail.  It really seems like a code issue between requesting C++11 and using `g++-4.9` -- and it is one that I had not seen before.

*Outlook:* The good news that R Core / CRAN are working on updating the toolchain to what is called `rtools4` with version 8.* of `gcc` and `g++` -- and the package builds fine there as it does on Linux.  So we could simply wait for R 4.0.0 on April of 2020 and hope that `rtools4` will be used by then,

**Comment by saligrama** [comment]
This could explain many of the issues I'm having compiling saligrama/rcorels on Windows.

**Comment by eddelbuettel** [comment]
Could be, but note that the code in `src/` changed somewhat.  

What I have here now builds under the upcoming (and likely to be released with R 4.0.0) toolchain based on a newer g++.  I verified that the code currently in corels will not build under g++ 4.9.* irrespective of the OS.

But anyway, cool to see you also built an R interface.  I was obviously unaware.

**Comment by nlarusstone** [comment]
This error looks like it's coming from our implementation in `alloc.hh`, which is where we modify the allocators to track memory. While useful for research and debugging, this is not something we need for our package.

I think the best solution would be to have a way to either use the tracking memory or not depending on the existence of `alloc.hh`. We could then keep `alloc.hh` locally, but not package it up.

Does R have a way to package only some of the files (the equivalent in python is setuptools' `find_packages(exclude=...)`)?

**Comment by eddelbuettel** [comment]
Absolutely -- via `.Rbuildignore` as [described here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#index-_002eRbuildignore-file).  So yes making the use of that header conditional would work.

(As would waiting for R 4.0.0 but we will have the problem with everybody using older compilers.)

**Comment by nlarusstone** [comment]
I'm happy with either -- if you or someone else wants to tackle this at some point, then great! If not, then we can wait until R 4.0.0.

I'll also mark this as a good starter issue for someone who wants to begin contributing on the project.

**Comment by eddelbuettel** [comment]
But it is not a matter of just excluding `alloc.h` -- it is also a matter of adding `#define` everywhere for the tracking data types.

**Comment by eddelbuettel** [comment]
... which I've now done.  And that builds on Windows.  Yay.

See https://github.com/eddelbuettel/rcppcorels/pull/2

**Comment by nlarusstone** [comment]
Amazing! Thanks so much for the help. Happy to merge that into master here if you submit a PR

**Comment by eddelbuettel** [comment]
There could probably a few micro-PRs we could do:
1. Standardize header file names, I have all .h rather than .hh
1. Small adjustment to pass R Policy checks so maybe add a 'R build?' define for Rprintf etc, let go of puts, ...
1. Conditional use of allocation tracking.

Shall we attack those topic by topic?

**Comment by nlarusstone** [comment]
Yes, can we create separate issues for each of these and then can have one PR per issue

**Comment by eddelbuettel** [comment]
That should now be taken care of via https://github.com/nlarusstone/corels/pull/21.
