### ISSUE TITLE
Minimize header file difference relative to R package

### ISSUE THREAD

**Issue by eddelbuettel** [nlarusstone/corels#18]
As discussed in #17 we can break changes down into a few manageable steps.

The first, and fairly simple one, would be to rename the header files from `*.hh` to `*.h`.  While the former is valid C++, it is less common in repos of extension packages.  I can submit a simple PR.

**Comment by nlarusstone** [comment]
Yup, sounds good to me! Looks like PR: https://github.com/nlarusstone/corels/pull/19
