### ISSUE TITLE
Data generation helper ?

### ISSUE THREAD

**Issue by eddelbuettel** [nlarusstone/corels#24]
Are there any helper functions to convert between the csv format (_i.e. `compas+{test,train}.csv`), the csv binary format and the custom format used here?  

I played a little with R`s `model.matrix()` but didn't get to 155 columns even when interacting all terms.  It is possible that I used the wrong contrasts code.  If there were an example script somewhere (here or over at the sbrl repo) I'd much appreciate a pointer.

**Comment by nlarusstone** [comment]
Hi @eddelbuettel, just added our processing code: https://github.com/nlarusstone/corels/tree/master/processing

Let me know if that doesn't work (and we can reopen this issue)!

**Comment by eddelbuettel** [comment]
I hackishly reverse engineered something from the pycorels repo, but it is not great.

Ultimately it would be nice to have something at the C++ layer all client packages could use.
