### ISSUE TITLE
did you tested you code vs: pyARC, QCBA, arc, arulesCBA, rCBA ?

### ISSUE THREAD

**Issue by Sandy4321** [nlarusstone/corels#26]
did you tested you code vs
https://github.com/jirifilip/pyARC
and
https://github.com/kliegr/QCBA
and
mentioned in
https://journal.r-project.org/archive/2019/RJ-2019-048/RJ-2019-048.pdf
Associative Classification in R: arc,
arulesCBA, and rCBA
PS
do you planning to take part in 

RuleML+RR 2020
4th International Joint Conference on Rules and Reasoning
29 June - 1 July 2020, Oslo, Norway
https://www.declarativeai.net/events/ruleml-rr/ruleml-rr-rc

**Comment by nlarusstone** [comment]
We have not, but feel free to compare and post the results!
