### ISSUE TITLE
Allowing sparse format for the input data

### ISSUE THREAD

**Issue by dominiqueemmanuel** [nlarusstone/corels#36]
Hi,

And thank you for this great work!

I wonder if it would be possible (and interesting), to allow a sparse format of the input data.

Currently, a feature is coded with 0 and 1.

However, it is very common for the number of 0's to be higher (and sometimes much higher) than the number of 1's. For example, if the features come from a bag of words, 1's are very rare and 0's very frequent.
In these cases, it would therefore be very advantageous to code the features sparsely (at least for the effective size of the input data, but perhaps also for some aspects of the computation?).

For example, a dense representation
```
{feature} 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0
```
would be transformed into a sparse representation (where only the indices of 1 are stored)
```
{feature} 5 11 15
```

What do you think about it?

Kind regards,
Dom

**Comment by cynrudin** [comment]
Hi - This comment is about the input to CORELS, which goes straight into a rule-mining algorithm. We don’t write the rule-mining algorithm, CORELS just selects and arranges the rules. So - you could find a rule-mining algorithm that takes sparse data as input, and take the resulting rules and feed them into CORELS. Cheers, Cynthia

**Comment by alabid** [comment]
And just to add to Cynthia’s points:
It’s not a dense representation since it’s stored as a bit vector (i.e., so 2082 in decimal). You could further sparsify this representation though but you’d have to consider the entire (binary) feature matrix and not one rule. And you’d have to consider if it adds any (further) value.

Best,
Daniel

**Comment by dominiqueemmanuel** [comment]
> Hi - This comment is about the input to CORELS, which goes straight into a rule-mining algorithm. We don’t write the rule-mining algorithm, CORELS just selects and arranges the rules. So - you could find a rule-mining algorithm that takes sparse data as input, and take the resulting rules and feed them into CORELS. Cheers, Cynthia
> […](#)
> On Nov 18, 2020, at 3:03 AM, Dominique EMMANUEL ***@***.***> wrote: Hi, And thank you for this great work! I wonder if it would be possible (and interesting), to allow a sparse format of the input data. Currently, a feature is coded with 0 and 1. However, it is very common for the number of 0's to be higher (and sometimes much higher) than the number of 1's. For example, if the features come from a bag of words, 1's are very rare and 0's very frequent. In these cases, it would therefore be very advantageous to code the features sparsely (at least for the effective size of the input data, but perhaps also for some aspects of the computation?). For example, a dense representation {feature} 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 would be transformed into a sparse representation (where only the indices of 1 are stored) {feature} 5 11 15 What do you think about it? Kind regards, Dom — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you! Your answer helps me to understand how CORELS is designed for.

Best regards,
Dominique

**Comment by cynrudin** [comment]
Good luck!
