### ISSUE TITLE
performance corels vs skope-rules 

### ISSUE THREAD

**Issue by Sandy4321** [nlarusstone/corels#8]
how different performance are vs https://github.com/scikit-learn-contrib/skope-rules

**Comment by nlarusstone** [comment]
It doesn't really make sense to compare the two methods as they're performing different functions.

I haven't used skope-rules before, but it looks to be a rule mining method.

CORELS is a rule list method, meaning we take already mined rules (we use the fpgrowth algorithm to mine rules) and then build the optimal classifier possible given those rules.

**Comment by Sandy4321** [comment]
Great thanks for soon answer, is it possible to extract mined rules by fpgrowth algorithm?
Hopefully you have same parameter to get access to these rules?

**Comment by nlarusstone** [comment]
Here's the fpgrowth algorithm that we use: http://www.borgelt.net/doc/fpgrowth/fpgrowth.html
