### ISSUE TITLE
Unbalanced data classification

### ISSUE THREAD

**Issue by Sandy4321** [nlarusstone/corels#9]
How to use unbalanced data, for example number of labels yes is 100 but number of labels no is 10000
Moreover , is it possible to set class waits by analogy with logistics regression in scikit learn
For example in practice it is important to increase probability of correct classification for one of targets
In example above , it can be answered yes

**Comment by nlarusstone** [comment]
Hi Sandy4321,

We don't do anything in particular for unbalanced data classification (e.g. class weighting). CORELS would probably not perform very well on a very unbalanced dataset, as its objective function would tend to classify as many samples correctly as possible.

However, the advantage of using CORELS is you can inspect the resulting trained model yourself and see if it's handling the unbalanced data in a reasonable way.

**Comment by nlarusstone** [comment]
Per @cynrudin's comments, there is actually a way to handle unbalanced data as follows:
"The solution to handling imbalanced data is to replicate the minority class. If you wanted the minority class to be twice as important, you just copy it twice and run CORELS as usual."

Let us know if that helps!
